// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.3
// source: biscuit.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicKey_Algorithm int32

const (
	PublicKey_Ed25519 PublicKey_Algorithm = 0
)

// Enum value maps for PublicKey_Algorithm.
var (
	PublicKey_Algorithm_name = map[int32]string{
		0: "Ed25519",
	}
	PublicKey_Algorithm_value = map[string]int32{
		"Ed25519": 0,
	}
)

func (x PublicKey_Algorithm) Enum() *PublicKey_Algorithm {
	p := new(PublicKey_Algorithm)
	*p = x
	return p
}

func (x PublicKey_Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublicKey_Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_biscuit_proto_enumTypes[0].Descriptor()
}

func (PublicKey_Algorithm) Type() protoreflect.EnumType {
	return &file_biscuit_proto_enumTypes[0]
}

func (x PublicKey_Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PublicKey_Algorithm) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PublicKey_Algorithm(num)
	return nil
}

// Deprecated: Use PublicKey_Algorithm.Descriptor instead.
func (PublicKey_Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{3, 0}
}

type Scope_ScopeType int32

const (
	Scope_Authority Scope_ScopeType = 0
	Scope_Previous  Scope_ScopeType = 1
)

// Enum value maps for Scope_ScopeType.
var (
	Scope_ScopeType_name = map[int32]string{
		0: "Authority",
		1: "Previous",
	}
	Scope_ScopeType_value = map[string]int32{
		"Authority": 0,
		"Previous":  1,
	}
)

func (x Scope_ScopeType) Enum() *Scope_ScopeType {
	p := new(Scope_ScopeType)
	*p = x
	return p
}

func (x Scope_ScopeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scope_ScopeType) Descriptor() protoreflect.EnumDescriptor {
	return file_biscuit_proto_enumTypes[1].Descriptor()
}

func (Scope_ScopeType) Type() protoreflect.EnumType {
	return &file_biscuit_proto_enumTypes[1]
}

func (x Scope_ScopeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Scope_ScopeType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Scope_ScopeType(num)
	return nil
}

// Deprecated: Use Scope_ScopeType.Descriptor instead.
func (Scope_ScopeType) EnumDescriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{6, 0}
}

type OpUnary_Kind int32

const (
	OpUnary_Negate OpUnary_Kind = 0
	OpUnary_Parens OpUnary_Kind = 1
	OpUnary_Length OpUnary_Kind = 2
)

// Enum value maps for OpUnary_Kind.
var (
	OpUnary_Kind_name = map[int32]string{
		0: "Negate",
		1: "Parens",
		2: "Length",
	}
	OpUnary_Kind_value = map[string]int32{
		"Negate": 0,
		"Parens": 1,
		"Length": 2,
	}
)

func (x OpUnary_Kind) Enum() *OpUnary_Kind {
	p := new(OpUnary_Kind)
	*p = x
	return p
}

func (x OpUnary_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpUnary_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_biscuit_proto_enumTypes[2].Descriptor()
}

func (OpUnary_Kind) Type() protoreflect.EnumType {
	return &file_biscuit_proto_enumTypes[2]
}

func (x OpUnary_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OpUnary_Kind) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OpUnary_Kind(num)
	return nil
}

// Deprecated: Use OpUnary_Kind.Descriptor instead.
func (OpUnary_Kind) EnumDescriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{15, 0}
}

type OpBinary_Kind int32

const (
	OpBinary_LessThan       OpBinary_Kind = 0
	OpBinary_GreaterThan    OpBinary_Kind = 1
	OpBinary_LessOrEqual    OpBinary_Kind = 2
	OpBinary_GreaterOrEqual OpBinary_Kind = 3
	OpBinary_Equal          OpBinary_Kind = 4
	OpBinary_Contains       OpBinary_Kind = 5
	OpBinary_Prefix         OpBinary_Kind = 6
	OpBinary_Suffix         OpBinary_Kind = 7
	OpBinary_Regex          OpBinary_Kind = 8
	OpBinary_Add            OpBinary_Kind = 9
	OpBinary_Sub            OpBinary_Kind = 10
	OpBinary_Mul            OpBinary_Kind = 11
	OpBinary_Div            OpBinary_Kind = 12
	OpBinary_And            OpBinary_Kind = 13
	OpBinary_Or             OpBinary_Kind = 14
	OpBinary_Intersection   OpBinary_Kind = 15
	OpBinary_Union          OpBinary_Kind = 16
)

// Enum value maps for OpBinary_Kind.
var (
	OpBinary_Kind_name = map[int32]string{
		0:  "LessThan",
		1:  "GreaterThan",
		2:  "LessOrEqual",
		3:  "GreaterOrEqual",
		4:  "Equal",
		5:  "Contains",
		6:  "Prefix",
		7:  "Suffix",
		8:  "Regex",
		9:  "Add",
		10: "Sub",
		11: "Mul",
		12: "Div",
		13: "And",
		14: "Or",
		15: "Intersection",
		16: "Union",
	}
	OpBinary_Kind_value = map[string]int32{
		"LessThan":       0,
		"GreaterThan":    1,
		"LessOrEqual":    2,
		"GreaterOrEqual": 3,
		"Equal":          4,
		"Contains":       5,
		"Prefix":         6,
		"Suffix":         7,
		"Regex":          8,
		"Add":            9,
		"Sub":            10,
		"Mul":            11,
		"Div":            12,
		"And":            13,
		"Or":             14,
		"Intersection":   15,
		"Union":          16,
	}
)

func (x OpBinary_Kind) Enum() *OpBinary_Kind {
	p := new(OpBinary_Kind)
	*p = x
	return p
}

func (x OpBinary_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpBinary_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_biscuit_proto_enumTypes[3].Descriptor()
}

func (OpBinary_Kind) Type() protoreflect.EnumType {
	return &file_biscuit_proto_enumTypes[3]
}

func (x OpBinary_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OpBinary_Kind) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OpBinary_Kind(num)
	return nil
}

// Deprecated: Use OpBinary_Kind.Descriptor instead.
func (OpBinary_Kind) EnumDescriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{16, 0}
}

type Policy_Kind int32

const (
	Policy_Allow Policy_Kind = 0
	Policy_Deny  Policy_Kind = 1
)

// Enum value maps for Policy_Kind.
var (
	Policy_Kind_name = map[int32]string{
		0: "Allow",
		1: "Deny",
	}
	Policy_Kind_value = map[string]int32{
		"Allow": 0,
		"Deny":  1,
	}
)

func (x Policy_Kind) Enum() *Policy_Kind {
	p := new(Policy_Kind)
	*p = x
	return p
}

func (x Policy_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Policy_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_biscuit_proto_enumTypes[4].Descriptor()
}

func (Policy_Kind) Type() protoreflect.EnumType {
	return &file_biscuit_proto_enumTypes[4]
}

func (x Policy_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Policy_Kind) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Policy_Kind(num)
	return nil
}

// Deprecated: Use Policy_Kind.Descriptor instead.
func (Policy_Kind) EnumDescriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{17, 0}
}

type Biscuit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RootKeyId *uint32        `protobuf:"varint,1,opt,name=rootKeyId" json:"rootKeyId,omitempty"`
	Authority *SignedBlock   `protobuf:"bytes,2,req,name=authority" json:"authority,omitempty"`
	Blocks    []*SignedBlock `protobuf:"bytes,3,rep,name=blocks" json:"blocks,omitempty"`
	Proof     *Proof         `protobuf:"bytes,4,req,name=proof" json:"proof,omitempty"`
}

func (x *Biscuit) Reset() {
	*x = Biscuit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Biscuit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Biscuit) ProtoMessage() {}

func (x *Biscuit) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Biscuit.ProtoReflect.Descriptor instead.
func (*Biscuit) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{0}
}

func (x *Biscuit) GetRootKeyId() uint32 {
	if x != nil && x.RootKeyId != nil {
		return *x.RootKeyId
	}
	return 0
}

func (x *Biscuit) GetAuthority() *SignedBlock {
	if x != nil {
		return x.Authority
	}
	return nil
}

func (x *Biscuit) GetBlocks() []*SignedBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *Biscuit) GetProof() *Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

type SignedBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block             []byte             `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	NextKey           *PublicKey         `protobuf:"bytes,2,req,name=nextKey" json:"nextKey,omitempty"`
	Signature         []byte             `protobuf:"bytes,3,req,name=signature" json:"signature,omitempty"`
	ExternalSignature *ExternalSignature `protobuf:"bytes,4,opt,name=externalSignature" json:"externalSignature,omitempty"`
}

func (x *SignedBlock) Reset() {
	*x = SignedBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedBlock) ProtoMessage() {}

func (x *SignedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedBlock.ProtoReflect.Descriptor instead.
func (*SignedBlock) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{1}
}

func (x *SignedBlock) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *SignedBlock) GetNextKey() *PublicKey {
	if x != nil {
		return x.NextKey
	}
	return nil
}

func (x *SignedBlock) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedBlock) GetExternalSignature() *ExternalSignature {
	if x != nil {
		return x.ExternalSignature
	}
	return nil
}

type ExternalSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature []byte     `protobuf:"bytes,1,req,name=signature" json:"signature,omitempty"`
	PublicKey *PublicKey `protobuf:"bytes,2,req,name=publicKey" json:"publicKey,omitempty"`
}

func (x *ExternalSignature) Reset() {
	*x = ExternalSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalSignature) ProtoMessage() {}

func (x *ExternalSignature) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalSignature.ProtoReflect.Descriptor instead.
func (*ExternalSignature) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{2}
}

func (x *ExternalSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ExternalSignature) GetPublicKey() *PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type PublicKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Algorithm *PublicKey_Algorithm `protobuf:"varint,1,req,name=algorithm,enum=PublicKey_Algorithm" json:"algorithm,omitempty"`
	Key       []byte               `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{3}
}

func (x *PublicKey) GetAlgorithm() PublicKey_Algorithm {
	if x != nil && x.Algorithm != nil {
		return *x.Algorithm
	}
	return PublicKey_Ed25519
}

func (x *PublicKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type Proof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//	*Proof_NextSecret
	//	*Proof_FinalSignature
	Content isProof_Content `protobuf_oneof:"Content"`
}

func (x *Proof) Reset() {
	*x = Proof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proof) ProtoMessage() {}

func (x *Proof) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proof.ProtoReflect.Descriptor instead.
func (*Proof) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{4}
}

func (m *Proof) GetContent() isProof_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *Proof) GetNextSecret() []byte {
	if x, ok := x.GetContent().(*Proof_NextSecret); ok {
		return x.NextSecret
	}
	return nil
}

func (x *Proof) GetFinalSignature() []byte {
	if x, ok := x.GetContent().(*Proof_FinalSignature); ok {
		return x.FinalSignature
	}
	return nil
}

type isProof_Content interface {
	isProof_Content()
}

type Proof_NextSecret struct {
	NextSecret []byte `protobuf:"bytes,1,opt,name=nextSecret,oneof"`
}

type Proof_FinalSignature struct {
	FinalSignature []byte `protobuf:"bytes,2,opt,name=finalSignature,oneof"`
}

func (*Proof_NextSecret) isProof_Content() {}

func (*Proof_FinalSignature) isProof_Content() {}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbols    []string     `protobuf:"bytes,1,rep,name=symbols" json:"symbols,omitempty"`
	Context    *string      `protobuf:"bytes,2,opt,name=context" json:"context,omitempty"`
	Version    *uint32      `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	FactsV2    []*FactV2    `protobuf:"bytes,4,rep,name=facts_v2,json=factsV2" json:"facts_v2,omitempty"`
	RulesV2    []*RuleV2    `protobuf:"bytes,5,rep,name=rules_v2,json=rulesV2" json:"rules_v2,omitempty"`
	ChecksV2   []*CheckV2   `protobuf:"bytes,6,rep,name=checks_v2,json=checksV2" json:"checks_v2,omitempty"`
	Scope      []*Scope     `protobuf:"bytes,7,rep,name=scope" json:"scope,omitempty"`
	PublicKeys []*PublicKey `protobuf:"bytes,8,rep,name=publicKeys" json:"publicKeys,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{5}
}

func (x *Block) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *Block) GetContext() string {
	if x != nil && x.Context != nil {
		return *x.Context
	}
	return ""
}

func (x *Block) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *Block) GetFactsV2() []*FactV2 {
	if x != nil {
		return x.FactsV2
	}
	return nil
}

func (x *Block) GetRulesV2() []*RuleV2 {
	if x != nil {
		return x.RulesV2
	}
	return nil
}

func (x *Block) GetChecksV2() []*CheckV2 {
	if x != nil {
		return x.ChecksV2
	}
	return nil
}

func (x *Block) GetScope() []*Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Block) GetPublicKeys() []*PublicKey {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

type Scope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//	*Scope_ScopeType_
	//	*Scope_Block
	Content isScope_Content `protobuf_oneof:"Content"`
}

func (x *Scope) Reset() {
	*x = Scope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{6}
}

func (m *Scope) GetContent() isScope_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *Scope) GetScopeType() Scope_ScopeType {
	if x, ok := x.GetContent().(*Scope_ScopeType_); ok {
		return x.ScopeType
	}
	return Scope_Authority
}

func (x *Scope) GetBlock() int64 {
	if x, ok := x.GetContent().(*Scope_Block); ok {
		return x.Block
	}
	return 0
}

type isScope_Content interface {
	isScope_Content()
}

type Scope_ScopeType_ struct {
	ScopeType Scope_ScopeType `protobuf:"varint,1,opt,name=scopeType,enum=Scope_ScopeType,oneof"`
}

type Scope_Block struct {
	Block int64 `protobuf:"varint,2,opt,name=block,oneof"`
}

func (*Scope_ScopeType_) isScope_Content() {}

func (*Scope_Block) isScope_Content() {}

type FactV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Predicate *PredicateV2 `protobuf:"bytes,1,req,name=predicate" json:"predicate,omitempty"`
}

func (x *FactV2) Reset() {
	*x = FactV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FactV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactV2) ProtoMessage() {}

func (x *FactV2) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactV2.ProtoReflect.Descriptor instead.
func (*FactV2) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{7}
}

func (x *FactV2) GetPredicate() *PredicateV2 {
	if x != nil {
		return x.Predicate
	}
	return nil
}

type RuleV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head        *PredicateV2    `protobuf:"bytes,1,req,name=head" json:"head,omitempty"`
	Body        []*PredicateV2  `protobuf:"bytes,2,rep,name=body" json:"body,omitempty"`
	Expressions []*ExpressionV2 `protobuf:"bytes,3,rep,name=expressions" json:"expressions,omitempty"`
	Scope       []*Scope        `protobuf:"bytes,4,rep,name=scope" json:"scope,omitempty"`
}

func (x *RuleV2) Reset() {
	*x = RuleV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleV2) ProtoMessage() {}

func (x *RuleV2) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleV2.ProtoReflect.Descriptor instead.
func (*RuleV2) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{8}
}

func (x *RuleV2) GetHead() *PredicateV2 {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *RuleV2) GetBody() []*PredicateV2 {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RuleV2) GetExpressions() []*ExpressionV2 {
	if x != nil {
		return x.Expressions
	}
	return nil
}

func (x *RuleV2) GetScope() []*Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type CheckV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queries []*RuleV2 `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
}

func (x *CheckV2) Reset() {
	*x = CheckV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckV2) ProtoMessage() {}

func (x *CheckV2) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckV2.ProtoReflect.Descriptor instead.
func (*CheckV2) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{9}
}

func (x *CheckV2) GetQueries() []*RuleV2 {
	if x != nil {
		return x.Queries
	}
	return nil
}

type PredicateV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  *uint64   `protobuf:"varint,1,req,name=name" json:"name,omitempty"`
	Terms []*TermV2 `protobuf:"bytes,2,rep,name=terms" json:"terms,omitempty"`
}

func (x *PredicateV2) Reset() {
	*x = PredicateV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredicateV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredicateV2) ProtoMessage() {}

func (x *PredicateV2) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredicateV2.ProtoReflect.Descriptor instead.
func (*PredicateV2) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{10}
}

func (x *PredicateV2) GetName() uint64 {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return 0
}

func (x *PredicateV2) GetTerms() []*TermV2 {
	if x != nil {
		return x.Terms
	}
	return nil
}

type TermV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//	*TermV2_Variable
	//	*TermV2_Integer
	//	*TermV2_String_
	//	*TermV2_Date
	//	*TermV2_Bytes
	//	*TermV2_Bool
	//	*TermV2_Set
	Content isTermV2_Content `protobuf_oneof:"Content"`
}

func (x *TermV2) Reset() {
	*x = TermV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TermV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermV2) ProtoMessage() {}

func (x *TermV2) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermV2.ProtoReflect.Descriptor instead.
func (*TermV2) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{11}
}

func (m *TermV2) GetContent() isTermV2_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *TermV2) GetVariable() uint32 {
	if x, ok := x.GetContent().(*TermV2_Variable); ok {
		return x.Variable
	}
	return 0
}

func (x *TermV2) GetInteger() int64 {
	if x, ok := x.GetContent().(*TermV2_Integer); ok {
		return x.Integer
	}
	return 0
}

func (x *TermV2) GetString_() uint64 {
	if x, ok := x.GetContent().(*TermV2_String_); ok {
		return x.String_
	}
	return 0
}

func (x *TermV2) GetDate() uint64 {
	if x, ok := x.GetContent().(*TermV2_Date); ok {
		return x.Date
	}
	return 0
}

func (x *TermV2) GetBytes() []byte {
	if x, ok := x.GetContent().(*TermV2_Bytes); ok {
		return x.Bytes
	}
	return nil
}

func (x *TermV2) GetBool() bool {
	if x, ok := x.GetContent().(*TermV2_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *TermV2) GetSet() *TermSet {
	if x, ok := x.GetContent().(*TermV2_Set); ok {
		return x.Set
	}
	return nil
}

type isTermV2_Content interface {
	isTermV2_Content()
}

type TermV2_Variable struct {
	Variable uint32 `protobuf:"varint,1,opt,name=variable,oneof"`
}

type TermV2_Integer struct {
	Integer int64 `protobuf:"varint,2,opt,name=integer,oneof"`
}

type TermV2_String_ struct {
	String_ uint64 `protobuf:"varint,3,opt,name=string,oneof"`
}

type TermV2_Date struct {
	Date uint64 `protobuf:"varint,4,opt,name=date,oneof"`
}

type TermV2_Bytes struct {
	Bytes []byte `protobuf:"bytes,5,opt,name=bytes,oneof"`
}

type TermV2_Bool struct {
	Bool bool `protobuf:"varint,6,opt,name=bool,oneof"`
}

type TermV2_Set struct {
	Set *TermSet `protobuf:"bytes,7,opt,name=set,oneof"`
}

func (*TermV2_Variable) isTermV2_Content() {}

func (*TermV2_Integer) isTermV2_Content() {}

func (*TermV2_String_) isTermV2_Content() {}

func (*TermV2_Date) isTermV2_Content() {}

func (*TermV2_Bytes) isTermV2_Content() {}

func (*TermV2_Bool) isTermV2_Content() {}

func (*TermV2_Set) isTermV2_Content() {}

type TermSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Set []*TermV2 `protobuf:"bytes,1,rep,name=set" json:"set,omitempty"`
}

func (x *TermSet) Reset() {
	*x = TermSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TermSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermSet) ProtoMessage() {}

func (x *TermSet) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermSet.ProtoReflect.Descriptor instead.
func (*TermSet) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{12}
}

func (x *TermSet) GetSet() []*TermV2 {
	if x != nil {
		return x.Set
	}
	return nil
}

type ExpressionV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ops []*Op `protobuf:"bytes,1,rep,name=ops" json:"ops,omitempty"`
}

func (x *ExpressionV2) Reset() {
	*x = ExpressionV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpressionV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionV2) ProtoMessage() {}

func (x *ExpressionV2) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionV2.ProtoReflect.Descriptor instead.
func (*ExpressionV2) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{13}
}

func (x *ExpressionV2) GetOps() []*Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

type Op struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//	*Op_Value
	//	*Op_Unary
	//	*Op_Binary
	Content isOp_Content `protobuf_oneof:"Content"`
}

func (x *Op) Reset() {
	*x = Op{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Op.ProtoReflect.Descriptor instead.
func (*Op) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{14}
}

func (m *Op) GetContent() isOp_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *Op) GetValue() *TermV2 {
	if x, ok := x.GetContent().(*Op_Value); ok {
		return x.Value
	}
	return nil
}

func (x *Op) GetUnary() *OpUnary {
	if x, ok := x.GetContent().(*Op_Unary); ok {
		return x.Unary
	}
	return nil
}

func (x *Op) GetBinary() *OpBinary {
	if x, ok := x.GetContent().(*Op_Binary); ok {
		return x.Binary
	}
	return nil
}

type isOp_Content interface {
	isOp_Content()
}

type Op_Value struct {
	Value *TermV2 `protobuf:"bytes,1,opt,name=value,oneof"`
}

type Op_Unary struct {
	Unary *OpUnary `protobuf:"bytes,2,opt,name=unary,oneof"`
}

type Op_Binary struct {
	Binary *OpBinary `protobuf:"bytes,3,opt,name=Binary,oneof"`
}

func (*Op_Value) isOp_Content() {}

func (*Op_Unary) isOp_Content() {}

func (*Op_Binary) isOp_Content() {}

type OpUnary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind *OpUnary_Kind `protobuf:"varint,1,req,name=kind,enum=OpUnary_Kind" json:"kind,omitempty"`
}

func (x *OpUnary) Reset() {
	*x = OpUnary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpUnary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpUnary) ProtoMessage() {}

func (x *OpUnary) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpUnary.ProtoReflect.Descriptor instead.
func (*OpUnary) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{15}
}

func (x *OpUnary) GetKind() OpUnary_Kind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return OpUnary_Negate
}

type OpBinary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind *OpBinary_Kind `protobuf:"varint,1,req,name=kind,enum=OpBinary_Kind" json:"kind,omitempty"`
}

func (x *OpBinary) Reset() {
	*x = OpBinary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpBinary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpBinary) ProtoMessage() {}

func (x *OpBinary) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpBinary.ProtoReflect.Descriptor instead.
func (*OpBinary) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{16}
}

func (x *OpBinary) GetKind() OpBinary_Kind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return OpBinary_LessThan
}

type Policy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queries []*RuleV2    `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
	Kind    *Policy_Kind `protobuf:"varint,2,req,name=kind,enum=Policy_Kind" json:"kind,omitempty"`
}

func (x *Policy) Reset() {
	*x = Policy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{17}
}

func (x *Policy) GetQueries() []*RuleV2 {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *Policy) GetKind() Policy_Kind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return Policy_Allow
}

type AuthorizerPolicies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbols  []string   `protobuf:"bytes,1,rep,name=symbols" json:"symbols,omitempty"`
	Version  *uint32    `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	Facts    []*FactV2  `protobuf:"bytes,3,rep,name=facts" json:"facts,omitempty"`
	Rules    []*RuleV2  `protobuf:"bytes,4,rep,name=rules" json:"rules,omitempty"`
	Checks   []*CheckV2 `protobuf:"bytes,5,rep,name=checks" json:"checks,omitempty"`
	Policies []*Policy  `protobuf:"bytes,6,rep,name=policies" json:"policies,omitempty"`
}

func (x *AuthorizerPolicies) Reset() {
	*x = AuthorizerPolicies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizerPolicies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizerPolicies) ProtoMessage() {}

func (x *AuthorizerPolicies) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizerPolicies.ProtoReflect.Descriptor instead.
func (*AuthorizerPolicies) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{18}
}

func (x *AuthorizerPolicies) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *AuthorizerPolicies) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *AuthorizerPolicies) GetFacts() []*FactV2 {
	if x != nil {
		return x.Facts
	}
	return nil
}

func (x *AuthorizerPolicies) GetRules() []*RuleV2 {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *AuthorizerPolicies) GetChecks() []*CheckV2 {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *AuthorizerPolicies) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type ThirdPartyBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PreviousKey *PublicKey   `protobuf:"bytes,1,req,name=previousKey" json:"previousKey,omitempty"`
	PublicKeys  []*PublicKey `protobuf:"bytes,2,rep,name=publicKeys" json:"publicKeys,omitempty"`
}

func (x *ThirdPartyBlockRequest) Reset() {
	*x = ThirdPartyBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdPartyBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyBlockRequest) ProtoMessage() {}

func (x *ThirdPartyBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyBlockRequest.ProtoReflect.Descriptor instead.
func (*ThirdPartyBlockRequest) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{19}
}

func (x *ThirdPartyBlockRequest) GetPreviousKey() *PublicKey {
	if x != nil {
		return x.PreviousKey
	}
	return nil
}

func (x *ThirdPartyBlockRequest) GetPublicKeys() []*PublicKey {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

type ThirdPartyBlockContents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload           []byte             `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	ExternalSignature *ExternalSignature `protobuf:"bytes,2,req,name=externalSignature" json:"externalSignature,omitempty"`
}

func (x *ThirdPartyBlockContents) Reset() {
	*x = ThirdPartyBlockContents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biscuit_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdPartyBlockContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyBlockContents) ProtoMessage() {}

func (x *ThirdPartyBlockContents) ProtoReflect() protoreflect.Message {
	mi := &file_biscuit_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyBlockContents.ProtoReflect.Descriptor instead.
func (*ThirdPartyBlockContents) Descriptor() ([]byte, []int) {
	return file_biscuit_proto_rawDescGZIP(), []int{20}
}

func (x *ThirdPartyBlockContents) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ThirdPartyBlockContents) GetExternalSignature() *ExternalSignature {
	if x != nil {
		return x.ExternalSignature
	}
	return nil
}

var File_biscuit_proto protoreflect.FileDescriptor

var file_biscuit_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x69, 0x73, 0x63, 0x75, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x97, 0x01, 0x0a, 0x07, 0x42, 0x69, 0x73, 0x63, 0x75, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72,
	0x6f, 0x6f, 0x74, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x72, 0x6f, 0x6f, 0x74, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x09, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x09, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x24, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x1c, 0x0a, 0x05, 0x70,
	0x72, 0x6f, 0x6f, 0x66, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0xa9, 0x01, 0x0a, 0x0b, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12,
	0x24, 0x0a, 0x07, 0x6e, 0x65, 0x78, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x07, 0x6e, 0x65,
	0x78, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x40, 0x0a, 0x11, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x52, 0x11, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x5b, 0x0a, 0x11, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x22, 0x6b, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12,
	0x32, 0x0a, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x2e, 0x41,
	0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x52, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69,
	0x74, 0x68, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x18, 0x0a, 0x09, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74,
	0x68, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x64, 0x32, 0x35, 0x35, 0x31, 0x39, 0x10, 0x00, 0x22,
	0x5e, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x20, 0x0a, 0x0a, 0x6e, 0x65, 0x78, 0x74,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a,
	0x6e, 0x65, 0x78, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x0e, 0x66, 0x69,
	0x6e, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x0e, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0x8e, 0x02, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x08, 0x66, 0x61, 0x63, 0x74, 0x73,
	0x5f, 0x76, 0x32, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x46, 0x61, 0x63, 0x74,
	0x56, 0x32, 0x52, 0x07, 0x66, 0x61, 0x63, 0x74, 0x73, 0x56, 0x32, 0x12, 0x22, 0x0a, 0x08, 0x72,
	0x75, 0x6c, 0x65, 0x73, 0x5f, 0x76, 0x32, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x52, 0x75, 0x6c, 0x65, 0x56, 0x32, 0x52, 0x07, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x56, 0x32, 0x12,
	0x25, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x5f, 0x76, 0x32, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x32, 0x52, 0x08, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x73, 0x56, 0x32, 0x12, 0x1c, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x52, 0x05, 0x73,
	0x63, 0x6f, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x52, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x73,
	0x22, 0x86, 0x01, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x73, 0x63,
	0x6f, 0x70, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x53, 0x63, 0x6f, 0x70, 0x65, 0x2e, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x54, 0x79, 0x70, 0x65, 0x48,
	0x00, 0x52, 0x09, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x05,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x05, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x28, 0x0a, 0x09, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x10, 0x01, 0x42, 0x09,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x34, 0x0a, 0x06, 0x46, 0x61, 0x63,
	0x74, 0x56, 0x32, 0x12, 0x2a, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x56, 0x32, 0x52, 0x09, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x22,
	0x9b, 0x01, 0x0a, 0x06, 0x52, 0x75, 0x6c, 0x65, 0x56, 0x32, 0x12, 0x20, 0x0a, 0x04, 0x68, 0x65,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x56, 0x32, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x20, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x56, 0x32, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x2f,
	0x0a, 0x0b, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x56, 0x32, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x1c, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06,
	0x2e, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x22, 0x2c, 0x0a,
	0x07, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x32, 0x12, 0x21, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x72,
	0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x75, 0x6c, 0x65,
	0x56, 0x32, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x22, 0x40, 0x0a, 0x0b, 0x50,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x56, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x05, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x54, 0x65, 0x72, 0x6d, 0x56, 0x32, 0x52, 0x05, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x22, 0xc9, 0x01,
	0x0a, 0x06, 0x54, 0x65, 0x72, 0x6d, 0x56, 0x32, 0x12, 0x1c, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x08, 0x76, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x07, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x07, 0x69, 0x6e, 0x74, 0x65, 0x67,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x04, 0x62, 0x6f,
	0x6f, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c,
	0x12, 0x1c, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x54, 0x65, 0x72, 0x6d, 0x53, 0x65, 0x74, 0x48, 0x00, 0x52, 0x03, 0x73, 0x65, 0x74, 0x42, 0x09,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x24, 0x0a, 0x07, 0x54, 0x65, 0x72,
	0x6d, 0x53, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x56, 0x32, 0x52, 0x03, 0x73, 0x65, 0x74, 0x22,
	0x25, 0x0a, 0x0c, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x56, 0x32, 0x12,
	0x15, 0x0a, 0x03, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x03, 0x2e, 0x4f,
	0x70, 0x52, 0x03, 0x6f, 0x70, 0x73, 0x22, 0x77, 0x0a, 0x02, 0x4f, 0x70, 0x12, 0x1f, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x54, 0x65,
	0x72, 0x6d, 0x56, 0x32, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a,
	0x05, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4f,
	0x70, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x48, 0x00, 0x52, 0x05, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x12,
	0x23, 0x0a, 0x06, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x4f, 0x70, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x48, 0x00, 0x52, 0x06, 0x42, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x42, 0x09, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0x58, 0x0a, 0x07, 0x4f, 0x70, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x4f, 0x70, 0x55, 0x6e, 0x61,
	0x72, 0x79, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x2a, 0x0a,
	0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x65, 0x67, 0x61, 0x74, 0x65, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x73, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x10, 0x02, 0x22, 0x89, 0x02, 0x0a, 0x08, 0x4f, 0x70,
	0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x22, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x4f, 0x70, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2e,
	0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0xd8, 0x01, 0x0a, 0x04, 0x4b,
	0x69, 0x6e, 0x64, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x65, 0x73, 0x73, 0x54, 0x68, 0x61, 0x6e, 0x10,
	0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x47, 0x72, 0x65, 0x61, 0x74, 0x65, 0x72, 0x54, 0x68, 0x61, 0x6e,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x65, 0x73, 0x73, 0x4f, 0x72, 0x45, 0x71, 0x75, 0x61,
	0x6c, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x47, 0x72, 0x65, 0x61, 0x74, 0x65, 0x72, 0x4f, 0x72,
	0x45, 0x71, 0x75, 0x61, 0x6c, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x71, 0x75, 0x61, 0x6c,
	0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x10, 0x05,
	0x12, 0x0a, 0x0a, 0x06, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06,
	0x53, 0x75, 0x66, 0x66, 0x69, 0x78, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x65, 0x67, 0x65,
	0x78, 0x10, 0x08, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x10, 0x09, 0x12, 0x07, 0x0a, 0x03,
	0x53, 0x75, 0x62, 0x10, 0x0a, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x75, 0x6c, 0x10, 0x0b, 0x12, 0x07,
	0x0a, 0x03, 0x44, 0x69, 0x76, 0x10, 0x0c, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x6e, 0x64, 0x10, 0x0d,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x72, 0x10, 0x0e, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x0f, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x6e,
	0x69, 0x6f, 0x6e, 0x10, 0x10, 0x22, 0x6a, 0x0a, 0x06, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12,
	0x21, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x56, 0x32, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69,
	0x65, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0e,
	0x32, 0x0c, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x22, 0x1b, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x09, 0x0a, 0x05,
	0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x65, 0x6e, 0x79, 0x10,
	0x01, 0x22, 0xcd, 0x01, 0x0a, 0x12, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x72,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x05,
	0x66, 0x61, 0x63, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x46, 0x61,
	0x63, 0x74, 0x56, 0x32, 0x52, 0x05, 0x66, 0x61, 0x63, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x05, 0x72,
	0x75, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x75, 0x6c,
	0x65, 0x56, 0x32, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x06, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x56, 0x32, 0x52, 0x06, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x12, 0x23, 0x0a, 0x08,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07,
	0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65,
	0x73, 0x22, 0x72, 0x0a, 0x16, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x0b, 0x70,
	0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x0b, 0x70, 0x72,
	0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x0a, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x73, 0x22, 0x75, 0x0a, 0x17, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61,
	0x72, 0x74, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x40, 0x0a, 0x11, 0x65, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x11, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x3b, 0x70, 0x62,
}

var (
	file_biscuit_proto_rawDescOnce sync.Once
	file_biscuit_proto_rawDescData = file_biscuit_proto_rawDesc
)

func file_biscuit_proto_rawDescGZIP() []byte {
	file_biscuit_proto_rawDescOnce.Do(func() {
		file_biscuit_proto_rawDescData = protoimpl.X.CompressGZIP(file_biscuit_proto_rawDescData)
	})
	return file_biscuit_proto_rawDescData
}

var file_biscuit_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_biscuit_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_biscuit_proto_goTypes = []interface{}{
	(PublicKey_Algorithm)(0),        // 0: PublicKey.Algorithm
	(Scope_ScopeType)(0),            // 1: Scope.ScopeType
	(OpUnary_Kind)(0),               // 2: OpUnary.Kind
	(OpBinary_Kind)(0),              // 3: OpBinary.Kind
	(Policy_Kind)(0),                // 4: Policy.Kind
	(*Biscuit)(nil),                 // 5: Biscuit
	(*SignedBlock)(nil),             // 6: SignedBlock
	(*ExternalSignature)(nil),       // 7: ExternalSignature
	(*PublicKey)(nil),               // 8: PublicKey
	(*Proof)(nil),                   // 9: Proof
	(*Block)(nil),                   // 10: Block
	(*Scope)(nil),                   // 11: Scope
	(*FactV2)(nil),                  // 12: FactV2
	(*RuleV2)(nil),                  // 13: RuleV2
	(*CheckV2)(nil),                 // 14: CheckV2
	(*PredicateV2)(nil),             // 15: PredicateV2
	(*TermV2)(nil),                  // 16: TermV2
	(*TermSet)(nil),                 // 17: TermSet
	(*ExpressionV2)(nil),            // 18: ExpressionV2
	(*Op)(nil),                      // 19: Op
	(*OpUnary)(nil),                 // 20: OpUnary
	(*OpBinary)(nil),                // 21: OpBinary
	(*Policy)(nil),                  // 22: Policy
	(*AuthorizerPolicies)(nil),      // 23: AuthorizerPolicies
	(*ThirdPartyBlockRequest)(nil),  // 24: ThirdPartyBlockRequest
	(*ThirdPartyBlockContents)(nil), // 25: ThirdPartyBlockContents
}
var file_biscuit_proto_depIdxs = []int32{
	6,  // 0: Biscuit.authority:type_name -> SignedBlock
	6,  // 1: Biscuit.blocks:type_name -> SignedBlock
	9,  // 2: Biscuit.proof:type_name -> Proof
	8,  // 3: SignedBlock.nextKey:type_name -> PublicKey
	7,  // 4: SignedBlock.externalSignature:type_name -> ExternalSignature
	8,  // 5: ExternalSignature.publicKey:type_name -> PublicKey
	0,  // 6: PublicKey.algorithm:type_name -> PublicKey.Algorithm
	12, // 7: Block.facts_v2:type_name -> FactV2
	13, // 8: Block.rules_v2:type_name -> RuleV2
	14, // 9: Block.checks_v2:type_name -> CheckV2
	11, // 10: Block.scope:type_name -> Scope
	8,  // 11: Block.publicKeys:type_name -> PublicKey
	1,  // 12: Scope.scopeType:type_name -> Scope.ScopeType
	15, // 13: FactV2.predicate:type_name -> PredicateV2
	15, // 14: RuleV2.head:type_name -> PredicateV2
	15, // 15: RuleV2.body:type_name -> PredicateV2
	18, // 16: RuleV2.expressions:type_name -> ExpressionV2
	11, // 17: RuleV2.scope:type_name -> Scope
	13, // 18: CheckV2.queries:type_name -> RuleV2
	16, // 19: PredicateV2.terms:type_name -> TermV2
	17, // 20: TermV2.set:type_name -> TermSet
	16, // 21: TermSet.set:type_name -> TermV2
	19, // 22: ExpressionV2.ops:type_name -> Op
	16, // 23: Op.value:type_name -> TermV2
	20, // 24: Op.unary:type_name -> OpUnary
	21, // 25: Op.Binary:type_name -> OpBinary
	2,  // 26: OpUnary.kind:type_name -> OpUnary.Kind
	3,  // 27: OpBinary.kind:type_name -> OpBinary.Kind
	13, // 28: Policy.queries:type_name -> RuleV2
	4,  // 29: Policy.kind:type_name -> Policy.Kind
	12, // 30: AuthorizerPolicies.facts:type_name -> FactV2
	13, // 31: AuthorizerPolicies.rules:type_name -> RuleV2
	14, // 32: AuthorizerPolicies.checks:type_name -> CheckV2
	22, // 33: AuthorizerPolicies.policies:type_name -> Policy
	8,  // 34: ThirdPartyBlockRequest.previousKey:type_name -> PublicKey
	8,  // 35: ThirdPartyBlockRequest.publicKeys:type_name -> PublicKey
	7,  // 36: ThirdPartyBlockContents.externalSignature:type_name -> ExternalSignature
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_biscuit_proto_init() }
func file_biscuit_proto_init() {
	if File_biscuit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_biscuit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Biscuit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FactV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredicateV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TermV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TermSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpressionV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Op); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpUnary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpBinary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Policy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizerPolicies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdPartyBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biscuit_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdPartyBlockContents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_biscuit_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Proof_NextSecret)(nil),
		(*Proof_FinalSignature)(nil),
	}
	file_biscuit_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*Scope_ScopeType_)(nil),
		(*Scope_Block)(nil),
	}
	file_biscuit_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*TermV2_Variable)(nil),
		(*TermV2_Integer)(nil),
		(*TermV2_String_)(nil),
		(*TermV2_Date)(nil),
		(*TermV2_Bytes)(nil),
		(*TermV2_Bool)(nil),
		(*TermV2_Set)(nil),
	}
	file_biscuit_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*Op_Value)(nil),
		(*Op_Unary)(nil),
		(*Op_Binary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_biscuit_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_biscuit_proto_goTypes,
		DependencyIndexes: file_biscuit_proto_depIdxs,
		EnumInfos:         file_biscuit_proto_enumTypes,
		MessageInfos:      file_biscuit_proto_msgTypes,
	}.Build()
	File_biscuit_proto = out.File
	file_biscuit_proto_rawDesc = nil
	file_biscuit_proto_goTypes = nil
	file_biscuit_proto_depIdxs = nil
}
